import type { AppPermissionDefinition } from "./types";

export const clerkPermissions: AppPermissionDefinition = {
  provider: "clerk",
  groups: [
    {
      category: "read",
      wildcard: {
        id: "read_all",
        name: "All read operations",
        description: "Read resources from the Clerk Backend API",
        hostPattern: "api.clerk.com",
        pathPattern: "/v1/*",
        method: "GET",
      },
      tools: [
        {
          id: "get_instance",
          name: "Get instance",
          description: "Get details about the current Clerk instance",
          hostPattern: "api.clerk.com",
          pathPattern: "/v1/instance",
          method: "GET",
        },
        {
          id: "list_users",
          name: "List users",
          description: "List users in the Clerk instance",
          hostPattern: "api.clerk.com",
          pathPattern: "/v1/users",
          method: "GET",
        },
        {
          id: "get_user",
          name: "Get user",
          description: "Get a specific Clerk user",
          hostPattern: "api.clerk.com",
          pathPattern: "/v1/users/*",
          method: "GET",
        },
        {
          id: "list_organizations",
          name: "List organizations",
          description: "List organizations in the Clerk instance",
          hostPattern: "api.clerk.com",
          pathPattern: "/v1/organizations",
          method: "GET",
        },
        {
          id: "get_organization",
          name: "Get organization",
          description: "Get a specific Clerk organization",
          hostPattern: "api.clerk.com",
          pathPattern: "/v1/organizations/*",
          method: "GET",
        },
        {
          id: "list_sessions",
          name: "List sessions",
          description: "List sessions in the Clerk instance",
          hostPattern: "api.clerk.com",
          pathPattern: "/v1/sessions",
          method: "GET",
        },
      ],
    },
    {
      category: "write",
      wildcard: {
        id: "write_all",
        name: "All write operations",
        description:
          "Create, update, and delete resources with the Clerk Backend API",
        hostPattern: "api.clerk.com",
        pathPattern: "/v1/*",
        methods: ["POST", "PATCH", "PUT", "DELETE"],
      },
      tools: [
        {
          id: "create_user",
          name: "Create user",
          description: "Create a new Clerk user",
          hostPattern: "api.clerk.com",
          pathPattern: "/v1/users",
          method: "POST",
        },
        {
          id: "update_user",
          name: "Update user",
          description: "Update a Clerk user",
          hostPattern: "api.clerk.com",
          pathPattern: "/v1/users/*",
          method: "PATCH",
        },
        {
          id: "delete_user",
          name: "Delete user",
          description: "Delete a Clerk user",
          hostPattern: "api.clerk.com",
          pathPattern: "/v1/users/*",
          method: "DELETE",
        },
        {
          id: "create_organization",
          name: "Create organization",
          description: "Create a new Clerk organization",
          hostPattern: "api.clerk.com",
          pathPattern: "/v1/organizations",
          method: "POST",
        },
        {
          id: "update_organization",
          name: "Update organization",
          description: "Update a Clerk organization",
          hostPattern: "api.clerk.com",
          pathPattern: "/v1/organizations/*",
          method: "PATCH",
        },
        {
          id: "revoke_session",
          name: "Revoke session",
          description: "Revoke an active Clerk session",
          hostPattern: "api.clerk.com",
          pathPattern: "/v1/sessions/*/revoke",
          method: "POST",
        },
      ],
    },
  ],
};
