import type { AppPermissionDefinition } from "./types";

export const flyioPermissions: AppPermissionDefinition = {
  provider: "flyio",
  groups: [
    {
      category: "read",
      tools: [
        {
          id: "list_apps",
          name: "List apps",
          description: "List all apps in the organization",
          hostPattern: "api.machines.dev",
          pathPattern: "/v1/apps",
          method: "GET",
        },
        {
          id: "get_app",
          name: "Get app",
          description: "Get details for a specific app",
          hostPattern: "api.machines.dev",
          pathPattern: "/v1/apps/*",
          method: "GET",
        },
        {
          id: "list_machines",
          name: "List Machines",
          description: "List all Machines for an app",
          hostPattern: "api.machines.dev",
          pathPattern: "/v1/apps/*/machines",
          method: "GET",
        },
        {
          id: "get_machine",
          name: "Get Machine",
          description: "Get details for a specific Machine",
          hostPattern: "api.machines.dev",
          pathPattern: "/v1/apps/*/machines/*",
          method: "GET",
        },
        {
          id: "list_volumes",
          name: "List volumes",
          description: "List all volumes for an app",
          hostPattern: "api.machines.dev",
          pathPattern: "/v1/apps/*/volumes",
          method: "GET",
        },
        {
          id: "get_volume",
          name: "Get volume",
          description: "Get details for a specific volume",
          hostPattern: "api.machines.dev",
          pathPattern: "/v1/apps/*/volumes/*",
          method: "GET",
        },
      ],
    },
    {
      category: "write",
      tools: [
        {
          id: "create_app",
          name: "Create app",
          description: "Create a new app",
          hostPattern: "api.machines.dev",
          pathPattern: "/v1/apps",
          method: "POST",
        },
        {
          id: "delete_app",
          name: "Delete app",
          description: "Delete an app",
          hostPattern: "api.machines.dev",
          pathPattern: "/v1/apps/*",
          method: "DELETE",
        },
        {
          id: "create_machine",
          name: "Create Machine",
          description: "Create a new Machine for an app",
          hostPattern: "api.machines.dev",
          pathPattern: "/v1/apps/*/machines",
          method: "POST",
        },
        {
          id: "update_machine",
          name: "Update Machine",
          description: "Update a Machine's configuration",
          hostPattern: "api.machines.dev",
          pathPattern: "/v1/apps/*/machines/*",
          method: "POST",
        },
        {
          id: "start_machine",
          name: "Start Machine",
          description: "Start a stopped Machine",
          hostPattern: "api.machines.dev",
          pathPattern: "/v1/apps/*/machines/*/start",
          method: "POST",
        },
        {
          id: "stop_machine",
          name: "Stop Machine",
          description: "Stop a running Machine",
          hostPattern: "api.machines.dev",
          pathPattern: "/v1/apps/*/machines/*/stop",
          method: "POST",
        },
        {
          id: "delete_machine",
          name: "Delete Machine",
          description: "Delete a Machine",
          hostPattern: "api.machines.dev",
          pathPattern: "/v1/apps/*/machines/*",
          method: "DELETE",
        },
        {
          id: "create_volume",
          name: "Create volume",
          description: "Create a new volume for an app",
          hostPattern: "api.machines.dev",
          pathPattern: "/v1/apps/*/volumes",
          method: "POST",
        },
        {
          id: "delete_volume",
          name: "Delete volume",
          description: "Delete a volume",
          hostPattern: "api.machines.dev",
          pathPattern: "/v1/apps/*/volumes/*",
          method: "DELETE",
        },
        {
          id: "manage_secrets",
          name: "Manage secrets",
          description: "Create or update app secrets",
          hostPattern: "api.machines.dev",
          pathPattern: "/v1/apps/*/secrets",
          method: "POST",
        },
        {
          id: "graphql",
          name: "GraphQL API",
          description:
            "Query or mutate via the Fly.io GraphQL API (api.fly.io/graphql — the legacy control-plane endpoint).",
          hostPattern: "api.fly.io",
          pathPattern: "/graphql",
          method: "POST",
        },
      ],
    },
  ],
};
